### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError: logits must be 2-dimensional

### ISSUE THREAD

**Issue by Ahmedest61** [cedrusx/deep_features#2]
Hi, Thank you for this work.

I'm trying to play with hfnet_tf.py but inside the infer(), it gives me an error saying:

**[[Node: pred/local_head/detector/Softmax = Softmax[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](pred/local_head/detector/Conv_1/BiasAdd)]]**
![mobileNV](https://user-images.githubusercontent.com/8188175/108591557-2696d680-738b-11eb-859d-a0ef99c7b467.JPG)

I've tried to debug this but couldn't find the culprit. Can you help me to resolve it, please.

**Comment by cedrusx** [comment]
Hi @Ahmedest61 thanks for trying out. I've not seen this issue on my machines. What version of tensorflow are you using? Could you try 1.14? I've checked in a [conda env config](https://github.com/cedrusx/deep_features/blob/master/environment.yml) fyr.

**Comment by Ahmedest61** [comment]
Solved it with tf=1.13.1. :)
